[pytest]
markers =
    unit: Atomic unit tests that run quickly and do not require infrastructure
    integration: Tests that require running infrastructure (db, minio, spark, etc)
testpaths = tests
python_files = test_*.py
addopts = -v
