{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalake.fullname" . }}-airflow-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "datalake.airflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  webserver-user: {{ .Values.airflow.webserverUser }}
  webserver-password: {{ .Values.airflow.webserverPassword }}
{{- end }}
