{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalake.fullname" . }}-postgres-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "datalake.postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.postgres.user }}
  password: {{ .Values.postgres.password }}
  database: {{ .Values.postgres.database }}
  tokern-password: {{ .Values.postgres.tokernUserPassword }}
{{- end }}
